apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colors-fanout-ingress-nginx
  namespace: colors-ns
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: akscolors.penguintrails.com
      http:
        paths:
          - path: /red
            pathType: Prefix
            backend:
              service:
                name: red-service-cluster-ip
                port:
                  number: 8080
          - path: /green
            pathType: Prefix
            backend:
              service:
                name: green-service-cluster-ip
                port:
                  number: 8080
          - path: /blue
            pathType: Prefix
            backend:
              service:
                name: blue-service-cluster-ip
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: red-service-cluster-ip
                port:
                  number: 8080